### ISSUE TITLE
Allatori

### ISSUE THREAD

**Issue by ghost** [java-deobfuscator/deobfuscator-gui#11]
Im want to deobfuscate minecraft plugins but in console [Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-3] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer
[ClassLoader] An attempt was made to load the library zip.dll
Initialization of VM took 164ms
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: daw
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 'zxYpG1
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 5
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾶ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: V}3|q2
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 7
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾴ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 'zxYpG1
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 5
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾶ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: V}3|q2
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 7
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾴ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 'zxYpG1
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 5
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾶ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: V}3|q2
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 7
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾴ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 'zxYpG1
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 5
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾶ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: V}3|q2
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 7
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾴ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 'zxYpG1
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 5
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾶ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: V}3|q2
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 7
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾴ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 'zxYpG1
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 5
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾶ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: V}3|q2
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 7
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾴ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 'zxYpG1
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 5
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾶ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: V}3|q2
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 7
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾴ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 'zxYpG1
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 5
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾶ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: V}3|q2
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 7
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾴ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 'zxYpG1
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 5
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾶ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: V}3|q2
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 7
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾴ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 'zxYpG1
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 5
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾶ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: V}3|q2
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: 7
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onPlayerJoin(Lorg/bukkit/event/player/PlayerJoinEvent;)V: ﾴ
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J onInteract(Lorg/bukkit/event/block/BlockBreakEvent;)V: \Hb^pJt^?o}BrFS_tLz
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/J ItemDrop(Lorg/bukkit/event/player/PlayerDropItemEvent;)V: \Hb^pJt^?icBa
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/L onPlayerCommandPreprocess(Lorg/bukkit/event/player/PlayerCommandPreprocessEvent;)V: 1
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/L onPlayerCommandPreprocess(Lorg/bukkit/event/player/PlayerCommandPreprocessEvent;)V: ?z?.?bu?b	:/0,1#u,<'u+&6;+0(0
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/L onPlayerCommandPreprocess(Lorg/bukkit/event/player/PlayerCommandPreprocessEvent;)V: d
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/L onPlayerCommandPreprocess(Lorg/bukkit/event/player/PlayerCommandPreprocessEvent;)V: ?7 oed
 i snee
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/L onPlayerCommandPreprocess(Lorg/bukkit/event/player/PlayerCommandPreprocessEvent;)V: jN~@|LIl
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/L onPlayerCommandPreprocess(Lorg/bukkit/event/player/PlayerCommandPreprocessEvent;)V: D/
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/L onPlayerCommandPreprocess(Lorg/bukkit/event/player/PlayerCommandPreprocessEvent;)V: >
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/L onPlayerCommandPreprocess(Lorg/bukkit/event/player/PlayerCommandPreprocessEvent;)V: %eln%
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/L onPlayerCommandPreprocess(Lorg/bukkit/event/player/PlayerCommandPreprocessEvent;)V: 
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/v/J ALLATORIxDEMO(Lorg/bukkit/Color;)Lr/z/z/z/v/J;: 

[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/v/J ALLATORIxDEMO(Lorg/bukkit/Color;)Lr/z/z/z/v/J;: 
'C&
%i0i,=,i;&h
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/v/J ALLATORIxDEMO()Lorg/bukkit/inventory/ItemStack;: -<%C$=;
(h
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/m onPlayerInteract(Lorg/bukkit/event/player/PlayerInteractEvent;)V: rw^eUgvYv\g
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/m onPlayerInteract(Lorg/bukkit/event/player/PlayerInteractEvent;)V: P6B=@vV-G,L,I=
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/m onPlayerInteract(Lorg/bukkit/event/player/PlayerInteractEvent;)V: t6p9
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/m onPlayerInteract(Lorg/bukkit/event/player/PlayerInteractEvent;)V: Nccbhoy
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/m onPlayerInteract(Lorg/bukkit/event/player/PlayerInteractEvent;)V: rw^eUgsmBf
[Thread-3] INFO com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer - Decrypted string in r/z/z/z/r/M onServerListPing(Lorg/bukkit/event/server/ServerListPingEvent;)V: ?z?.b?$%4%?l0,!''?blu?3ou?c?9='u

why is problem ?

**Comment by ThisTestUser** [comment]
You have to upload your JAR.
And next time, you should create an issue here: https://github.com/java-deobfuscator/deobfuscator/issues

**Comment by ghost** [comment]
[dd.zip](https://github.com/java-deobfuscator/deobfuscator-gui/files/2119421/dd.zip)

this is minecraft plugin 


my transformers:
allatori.string.StringEncryptionTransformer

**Comment by ghost** [comment]
/util/Iterator could not be found while writing r/z/z/z/j/J. Using COMPUTE_MAXS
I have something like that at the end 
my config:
input: C:\Users\Piotr\Desktop\java-deob2\lalacore2.jar
output: C:\Users\Piotr\Desktop\java-deob2\deobed.jar
smartRedo: no
Verify: no
Detect: No
Transformers: allatori.string.StringEncryptionTransformer (I do not know what should be given to the allatori)

Path: C:\Users\Piotr\Desktop\java-deob2\spigot.
Libraries: C:\Users\Piotr\Desktop\java-deob2\spigot.jar



IgnoredClasses: No

**Comment by ThisTestUser** [comment]
[lalacore2Deob.zip](https://github.com/java-deobfuscator/deobfuscator-gui/files/2119853/lalacore2Deob.zip)
The transformer needs to be run 5 times because the person who obfuscated it used allatori 5 times.

**Comment by fikawka** [comment]
Thank you, plugin rozkodował August correctinie, but in the consola I have something like:
Error: java / util / Iterator could not be found while writing r / z / z / z / j / J. Using COMPUTE_MAXS
  And I have a question, what transformers should I use to decode the rest of .jar encoded in the allatori?

**Comment by ghost** [comment]
Thank you, but I have a question. What transformers to use to deobfuscate allatori?

**Comment by ThisTestUser** [comment]
allatori.string.StringEncryptionTransformer, but you have to run it 5 times.

**Comment by ghost** [comment]
That's why L.ALLATORIxDEM is not deobfuscated

**Comment by fikawka** [comment]
string deobfuscated all
