### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JuanCC22** [java-deobfuscator/deobfuscator-gui#12]
I cant deobfuscate that https://www33.zippyshare.com/v/Eg8sXd8S/file.html

Can someone do it for me , thanks

**Comment by ThisTestUser** [comment]
[testDeob.zip](https://github.com/java-deobfuscator/deobfuscator-gui/files/2119843/testDeob.zip)

**Comment by JuanCC22** [comment]
Is not working , i dont see any class filel

**Comment by ThisTestUser** [comment]
Some of the class files are in folders with no names. You can extract them with WinRAR.

**Comment by JuanCC22** [comment]
Well i cant extract it , it gives me a error cause it dont have a name , fix it please

**Comment by JuanCC22** [comment]
Also you give me a bad .rar i think when i open the API.class

It gives this  

Êþº¾   4 Y sv/file14/procosmetics/api/API  java/lang/Object  c Lsv/file14/procosmetics/Core; <init>  (Lsv/file14/procosmetics/Core;)V ()V  	
  
  	   giveCosmeticMenu (Lorg/bukkit/entity/Player;)V org/bukkit/entity/Player  isOnline ()Z     sv/file14/procosmetics/Core  IiIIiIiIIIIIIIIIiiIiÃƒÂ­ ‰()Lsv/file14/procosmetics/ / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / /IIiIIiiiIiiiIiiiiiiIÃƒÂ­;  
   …sv/file14/procosmetics/ / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / /IIiIIiiiIiiiIiiiiiiIÃƒÂ­   
   openMainMenu ‰()Lsv/file14/procosmetics/ / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / /IiIiiiIIiIIiiIIIiIiIÃƒÂ­;  !
  " ‰()Lsv/file14/procosmetics/ / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / /IIiIIiIiiIiiIiIIIIiiÃƒÂ­;  $
  % …sv/file1

Please before  giving me the  deobfuscated  test  it.ñ

**Comment by ThisTestUser** [comment]
You need to use a decompiler, like Bytecode viewer.

**Comment by JuanCC22** [comment]
Now yes , but  why i dont see any file, i just see api and core

**Comment by ThisTestUser** [comment]
Click on the packages, it should be inside.

**Comment by JuanCC22** [comment]
Nothing , can u give me the .rar with all the .class please

**Comment by ThisTestUser** [comment]
[testDeob.zip](https://github.com/java-deobfuscator/deobfuscator-gui/files/2121567/testDeob.zip)

**Comment by ghost** [comment]
> [testDeob.zip](https://github.com/java-deobfuscator/deobfuscator-gui/files/2121567/testDeob.zip)

Can you explain how you deobfuscated this instead giving the file you deobfuscated...
What the transformer you used ?

**Comment by ThisTestUser** [comment]
Since it has been so long, and the original file has been removed, I don't know.

**Comment by mopmop682** [comment]
> Since it has been so long, and the original file has been removed, I don't know.

Do you do the DEOBF in exchange for money?
