### ISSUE TITLE
<-> Add Copy Console logs <-> 

### ISSUE THREAD

**Issue by Jerem584** [java-deobfuscator/deobfuscator-gui#15]
Will be really nice.

im trying to find specific string and its really hard to find the string and i can't copy all the things because its too large so rip me. 

Will be nice to do options, log to file :)

**Comment by ThisTestUser** [comment]
Have you tried using CRTL-A to copy the entire Console?

**Comment by Janmm14** [comment]
It is possible to use CTRL-A CTRL-C to copy the console output.
