### ISSUE TITLE
Unable to create config.yml

### ISSUE THREAD

**Issue by biepie70** [java-deobfuscator/deobfuscator-gui#16]
i need a sample config file which you use to deobfuscate alltori obfuscated samples. There are a lot of malware samples floating around which are obfuscated using allatori and i need to analyze them as soon as possible.

**Comment by ThisTestUser** [comment]
You do not need a config.yml if you use the GUI. Simply select the input, output, libraries, and allatori.StringEncryptionTransformer (if you see string encryption) and/or allatori.FlowObfuscationTransformer (if you see decompiling errors).
