### ISSUE TITLE
Transformers arent loading

### ISSUE THREAD

**Issue by ghost** [java-deobfuscator/deobfuscator-gui#2]
"Failed to load transformers!" If i put the jar file in the gui. Any fixes? Or do i something wrong?

**Comment by ThisTestUser** [comment]
You need to download deobfuscator.jar there and select that as your deobfuscator jar.

**Comment by ghost** [comment]
As i said i downloaded the jar and put it in the field Deobfuscator Jar:
See: https://gyazo.com/e161edd72d749d9baafc0cd8ddcb4ad3

**Comment by ThisTestUser** [comment]
You need to select the actual jar file. In the picture you only selected the folder.

**Comment by ghost** [comment]
No this is actually the .jar file

**Comment by ghost** [comment]
Okay nvm it didnt took the jar from the Downloads folder, but when i moved it into the Documents folder it took the jar. Lmao
Just one more problem i must add the libary rt.jar but i get a java heap space. Do you know how i can add more ram to the programm or just fix it?

**Comment by ThisTestUser** [comment]
Run the GUI via the command line with the extra memory argument.
