### ISSUE TITLE
Can not deObfuscate file At all

### ISSUE THREAD

**Issue by payam59** [java-deobfuscator/deobfuscator-gui#20]
https://anonfile.com/Bdccad34ne/Protected_jar
using this deobfuscator , it will tell to use source file normalizer but it does no good

**Comment by ThisTestUser** [comment]
[ProtectedDeob.zip](https://github.com/java-deobfuscator/deobfuscator-gui/files/3513582/ProtectedDeob.zip)
Please use https://github.com/java-deobfuscator/deobfuscator for issues related to the deobfuscator next time.

**Comment by payam59** [comment]
Will you be kind enough to tell mw how did you deobfuscated this program?

**Comment by ThisTestUser** [comment]
It's a custom deobfuscator that I can't share.

**Comment by payam59** [comment]
Thank you for your help. Is there a way you can guid me is it possible to
deobfuscate it with public deobfuscator that you already have in github??
