### ISSUE TITLE
Deobfuscation

### ISSUE THREAD

**Issue by jetemange** [java-deobfuscator/deobfuscator-gui#23]
hello i want deobfuscate a plugin but i have this error
![image](https://user-images.githubusercontent.com/19253572/67879940-1a578c00-fb3e-11e9-9283-e5a98aa04704.png)

My config: 
![image](https://user-images.githubusercontent.com/19253572/67880010-35c29700-fb3e-11e9-82b5-64fd13517cb3.png)

**Comment by Janmm14** [comment]
that is no error

**Comment by ThisTestUser** [comment]
Don't check "verify", and use stringer.StringEncryptionTransformer. Also please use the issue tracker in deobfuscator: https://github.com/java-deobfuscator/deobfuscator

**Comment by Janmm14** [comment]
And remove detect check
