### ISSUE TITLE
Deobfuscation error java.lang.ArrayIndexOutOfBoundsException on read source file

### ISSUE THREAD

**Issue by Bibon21** [java-deobfuscator/deobfuscator-gui#25]
`java.lang.ArrayIndexOutOfBoundsException: 6930 at com.javadeobfuscator.org.objectweb.asm.ClassReader.readStringish(ClassReader.java:2659) at com.javadeobfuscator.org.objectweb.asm.ClassReader.readClass(ClassReader.java:2676) at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1628) at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126) at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698) at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500) at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:187) at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:173) at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:249) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74) at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812) at java.lang.Thread.run(Unknown Source)`
Please deobfuscate -> https://github.com/javadeobfuscator/deobfuscator/files/4032120/mod.zip

**Comment by ThisTestUser** [comment]
This is a deobfuscator error, go post this here: https://github.com/java-deobfuscator/deobfuscator/issues
