### ISSUE TITLE
You need a JVM with Java FX

### ISSUE THREAD

**Issue by Jacobtims** [java-deobfuscator/deobfuscator-gui#39]
When I launch deobfuscator-gui.jar, I get a error message called: **You need a JVM with JavaFX (an non-headless installation). Could not find class javafx/embed/swing/JFXPanel**.
![ErrorJVM](https://user-images.githubusercontent.com/75219092/129543240-43aa5b43-3ddc-4025-b5a8-27cfd472e8d1.JPG)

**Comment by Janmm14** [comment]
The easiest way to get a java installation with javafx is to use Zulu Java builds:
https://www.azul.com/downloads/?package=jre-fx#download-openjdk

You might have to scroll down a little on that page and make sure the package type is either JRE FX or JDK FX

An alternarive is to look for OpenJFX, however its installation is not straightforward

**Comment by Jacobtims** [comment]
And how can I launch it now with javafx?
I have it installed now, but it gives the same error...

**Comment by Janmm14** [comment]
Right click jar, choose "open with...", tick checkbox use as default, click more, scroll down, click choose other app from pc, select `javaw.exe` in bin directory from your zulu java installation.

**Comment by Jacobtims** [comment]
It still gives the same error. 😥

**Comment by Janmm14** [comment]
~~Open regedit, go to `HKEY_CLASSES_ROOT\jar_auto_file\shell\open\command` and replace the value `"C:\your\path\zulu\install\bin\javaw.exe" "%1"` with `"C:\your\path\zulu\install\bin\javaw.exe" -jar "%1"`~~ Doesn't work in my test.

Other strategy which works for me:
Put your zulu install bin directory into your Path, them create start.bat in the same folder as your deobfuscator-gui.jar and write this inside:
```cmd
@echo off
cd /D "%~dp0"
start javaw -jar deobfuscator-gui.jar
```

**Comment by Jacobtims** [comment]
Yeah, its working.
Thx!

**Comment by verx1337** [comment]
> ~Open regedit, go to `HKEY_CLASSES_ROOT\jar_auto_file\shell\open\command` and replace the value `"C:\your\path\zulu\install\bin\javaw.exe" "%1"` with `"C:\your\path\zulu\install\bin\javaw.exe" -jar "%1"`~ Doesn't work in my test.
> 
> Other strategy which works for me:
> Put your zulu install bin directory into your Path, them create start.bat in the same folder as your deobfuscator-gui.jar and write this inside:
> 
> ```
> @echo off
> cd /D "%~dp0"
> start javaw -jar deobfuscator-gui.jar
> ```

I tried this and it still didn't work :/

**Comment by Janmm14** [comment]
What is the output of `java -version` in cmd? Does it show something with Zulu?

**Comment by verx1337** [comment]
> What is the output of `java -version` in cmd? Does it show something with Zulu?

Nvm I fixed it thanks for the lookout tho

**Comment by mrlolua19** [comment]
> ~Open regedit, go to `HKEY_CLASSES_ROOT\jar_auto_file\shell\open\command` and replace the value `"C:\your\path\zulu\install\bin\javaw.exe" "%1"` with `"C:\your\path\zulu\install\bin\javaw.exe" -jar "%1"`~ Doesn't work in my test.
> 
> Other strategy which works for me: Put your zulu install bin directory into your Path, them create start.bat in the same folder as your deobfuscator-gui.jar and write this inside:
> 
> ```
> @echo off
> cd /D "%~dp0"
> start javaw -jar deobfuscator-gui.jar
> ```

What does %~dp0 mean?

**Comment by SSund3c** [comment]
> ~Open regedit, go to `HKEY_CLASSES_ROOT\jar_auto_file\shell\open\command` and replace the value `"C:\your\path\zulu\install\bin\javaw.exe" "%1"` with `"C:\your\path\zulu\install\bin\javaw.exe" -jar "%1"`~ Doesn't work in my test.
> 
> Other strategy which works for me: Put your zulu install bin directory into your Path, them create start.bat in the same folder as your deobfuscator-gui.jar and write this inside:
> 
> ```
> @echo off
> cd /D "%~dp0"
> start javaw -jar deobfuscator-gui.jar
> ```
It didn't help

**Comment by Janmm14** [comment]
> > ~Open regedit, go to `HKEY_CLASSES_ROOT\jar_auto_file\shell\open\command` and replace the value `"C:\your\path\zulu\install\bin\javaw.exe" "%1"` with `"C:\your\path\zulu\install\bin\javaw.exe" -jar "%1"`~ Doesn't work in my test.
> > Other strategy which works for me: Put your zulu install bin directory into your Path, them create start.bat in the same folder as your deobfuscator-gui.jar and write this inside:
> > ```
> > @echo off
> > cd /D "%~dp0"
> > start javaw -jar deobfuscator-gui.jar
> > ```
> 
> It didn't help

with just "it didn't help" there is absolutely no useful information on which steps you have tried (like did you actually install zulu jdk+fx or did you jsut scroll down to the latest post and tried it without reading previous stuff) and on what error message you actually recieved (in worst cae, do a screenshot and add it to your post).

Either way, please **do not answer here** on that topic, this is not a pc help forum.

Try programming or offtopic section on spigotmc.org forums for example and make sure to provide some sort of information, people generally do not have an almighty glass sphere.

**Comment by LostPlugins** [comment]
For anyone Trying to get it to work. Just call the correct javaw file directly so you don't have to worry about it using the default java path

```cmd
@echo off

cd /D "%~dp0"

start C:\Users\User\Desktop\Deob\bin\javaw -jar deobfuscator-gui.jar
```

**Comment by ghost** [comment]
@LostPlugins  I still the error after all this
