### ISSUE TITLE
You need a JVM with JavaFX

### ISSUE THREAD

**Issue by NoSleepYa** [java-deobfuscator/deobfuscator-gui#43]
Whenever I try to launch the gui I get an error message reading "could not find class javafx/embed/swing/JFXPanel" and nothing else launches. Anyone else with that issue?

**Comment by Janmm14** [comment]
Many OpenJDK builds nowadays do not include JavaFX.

You can download a jvm with javafx for example from https://www.azul.com/downloads/?package=jdk-fx (scroll down to the table)
(You don't get a windows installer for older Java versions marked STS)
Help for windows: https://docs.azul.com/core/zulu-openjdk/install/windows
Help for linux: https://docs.azul.com/core/zulu-openjdk/install/debian

Afaik Oracle propietary builds still include java fx, but the license and login requirement is meh.

**Comment by Janmm14** [comment]
See #35, #39, #41
