### ISSUE TITLE
config

### ISSUE THREAD

**Issue by Garrry4** [java-deobfuscator/deobfuscator-gui#45]
Anyone have a good config for this?

**Comment by Janmm14** [comment]
There is no "good config".
There is no "one config fits all".

If you do not have the knowledge about obfuscation, please read:

Tutorial: https://github.com/java-deobfuscator/deobfuscator/wiki/Getting-Started
Common errors help: https://github.com/java-deobfuscator/deobfuscator/tree/master/commonerrors
