### ISSUE TITLE
You need a JVM with JavaFX (an non-headless installation). Could not find class javafx/embed/swing/JFXPanel.

### ISSUE THREAD

**Issue by master7720** [java-deobfuscator/deobfuscator-gui#56]
tried everything you said too do in https://github.com/java-deobfuscator/deobfuscator-gui/issues/39 but it still doesnt work

**Comment by Janmm14** [comment]
Output of `java -version`?

**Comment by master7720** [comment]
**OpenJDK Runtime Environment (Zulu 8.64.0.15-CA-win64) (build 1.8.0_342-b07)
OpenJDK 64-Bit Server VM (Zulu 8.64.0.15-CA-win64) (build 25.342-b07, mixed mode)
*

**Comment by master7720** [comment]
nvm my buddy xeon fixed it in a pr
