### ISSUE TITLE
Please unpack error 

### ISSUE THREAD

**Issue by nguyenvanthinhdev** [java-deobfuscator/deobfuscator-gui#59]
https://drive.google.com/file/d/1DRADGScNehLzRM1wOCWSGgQb2O6SVTul/view?usp=sharing

help
please unpack 2 file

thanks.

**Comment by nguyenvanthinhdev** [comment]
If you can't download it, here's the link

https://1drv.ms/u/s!AiehxKAsGbpSgfsdnG-UQO2Fw5SYfQ?e=OlBaXe

**Comment by Janmm14** [comment]
We do NOT provide deobfuscation services.

You can wire me 500€ and I'll try my best tho xd.

Closed due to #48
